#!/usr/bin/env bash

# Insure that the local bin is on the PATH
[[ ! ":$PATH:" == *":${1}:"* ]] && export PATH=~/.local/bin:$PATH

# Insure that the local bin exists
mkdir -p ~/.local/bin


[ -z $BCH_000_INITIALIZED ] && {
    # Do what is normally done via [~/.profile]
    export BCH_000_INITIALIZED=1
    exit () { echo 'try: builtin exit' ; }
}
