#!/usr/bin/env bash
mkdir -p ~/.local/bin
for s in $(ls ${HOME}/.config/bch/lbin/bch*); do
    d=~/.local/bin/$(basename $s)
    [ ! -f $d ] && ln -s $s $d
done

source bch.000.bash_colors.sh
source bch.000.fun.sh
