#!/usr/bin/env bash

bch:000:link ~/.config/bch/vendor/bash_colors.sh       bch.000.bash_colors.sh
bch:000:link ~/.config/bch/vendor/bash-fun/src/fun.sh  bch.000.fun.sh
bch:000:link ~/.config/bch/vendor/bats/bin/bats        bch.000.bats

source bch.000.bash_colors.sh
source bch.000.fun.sh
