#!/usr/bin/env bash

which uv || curl -LsSf https://astral.sh/uv/install.sh | sh
#[ -f ${HOME}/.cargo/env ] || bch:000:note "missing file [~/.cargo/env]"
#[ -f ${HOME}/.cargo/env ] && source ${HOME}/.cargo/env
#source ${HOME}/.cargo/env
