#!/usr/bin/env bash

bch:000:clone () {
    local flag=${BCH_000_BCH_ROOT}/flag.is.cloned
    local repo
    local src
    local dst
    [ $1. == -f. ] && rm -f $flag
    [ -f $flag ] && return
    for repo in $(gh listall | grep ^bch\.[0-9][0-9][0-9]\. | sort); do
        src=git@github.com:bryanhann/${repo}
        dst=${BCH_000_BCH_ROOT}/${repo}
        [   -e $dst ] && bch:000:debug found repo ${repo}
        [   -e $dst ] && continue
        [ ! -e $dst ] && bch:000:debug "}}} git clone ${src} ${dst}"
        [ ! -e $dst ] && git clone ${src} ${dst}
    done
    touch $flag
}

