#!/usr/bin/env bash

__repos () {
    gh repo list --no-archived -L 1000 --json name,owner --jq .[].name 
}

bch:000:clone () {
    local flag=${BCH_000_BCH_ROOT}/flag.is.cloned
    local repo
    local src
    local dst
    [ $1. == -f. ] && rm -f $flag
    [ -f $flag ] && return
    for repo in $(__repos | grep ^bch\.[0-9][0-9][0-9]\. | sort); do
        src=git@github.com:bryanhann/${repo}
        dst=${BCH_000_BCH_ROOT}/${repo}
        [   -e $dst ] && ::dbg:: found repo ${repo}
        [   -e $dst ] && continue
        [ ! -e $dst ] && ::dbg:: "}}} git clone ${src} ${dst}"
        [ ! -e $dst ] && gh repo clone ${src} ${dst}
    done
    touch $flag
}

