#!/usr/bin/env bash

bch:000:activate () {
    local repo
    local target
    for repo in $(ls ${BCH_000_BCH_ROOT} | grep ^bch.[0-9] | sort); do
        ::dbg:: " . ${target}"
        #::dbg:: "    activating repo: $repo"
        target=${BCH_000_BCH_ROOT}/${repo}/.bch/activate.sh
        [ -f ${target} ] || continue
        source ${target}
    done
}
