#!/usr/bin/env bash

cd $(dirname $0)

which stow && {
    stow . --dotfiles -d ${PWD}/root.d -t ~
    exit
}

[ -d ~/hold ] && echo ~/hold already exists. quitting.
[ -d ~/hold ] && exit
mkdir ~/hold
mv ~/.bashrc ~/hold/
mv ~/.profile ~/hold
mv ~/.config ~/hold
ln -s ${PWD}/root.d/dot-bashrc ~/.bashrc
ln -s ${PWD}/root.d/dot-profile ~/.profile
ln -s ${PWD}/root.d/dot-config ~/.config


