#!/usr/bin/env bash

[ -f ~/DEBUG ] && echo "[:dbg:] ++[$BASH_SOURCE]"
source ${HOME}/.config/bch/activate.sh
[ -f ~/DEBUG ] && echo "[:dbg:] --[$BASH_SOURCE]"

#==END OF SCRIPT===================================
